import type { VillageFormState } from "@/lib/villages/form-types";

export const emptyParkingGuide = (): VillageFormState["parking_guide"] => ({
  cost: "",
  map_url: null,
  best_time: "",
  main_detail: "",
  main_location: "",
  overflow_note: "",
  on_street_note: "",
});

export const defaultVillageFormState = (): VillageFormState => ({
  name: "",
  slug: "",
  region_label: "",
  cotswolds_region: "",
  tagline_quote: "",
  brief_summary: "",
  brief_best_tip: "",
  overview_heading: "",
  overview_body: "",
  overview_image_url: "",
  time_needed: "",
  dog_friendly: "",
  best_season: "",
  score_first_time_visitor: 3,
  score_couples: 3,
  score_families: 3,
  score_food_drink: 3,
  score_accessibility: 3,
  score_hidden_gem_factor: 3,
  our_take_body: "",
  visited_date: "",
  reviewed_by_name: "",
  reviewed_by_credential: "",
  crowd_intelligence_note: "",
  crowd_times: [],
  perfect_for: [],
  maybe_skip_if: [],
  comparison_stats: [],
  alternative_villages: [],
  local_tips: [],
  hidden_gems: [],
  things_to_do: [],
  combine_with: [],
  places_to_stay: [],
  places_to_eat: [],
  local_businesses: [],
  parking_guide: emptyParkingGuide(),
  getting_here_rail: "",
  getting_here_parking: "",
  accessibility_wheelchair: "",
  accessibility_pushchair: "",
  accessibility_mobility_notes: "",
  accessibility_surface: "",
  rainy_day_options: [],
  faq_items: [],
  nearby_villages: [],
  meta_title: "",
  meta_description: "",
  alt_text: "",
  video_embed_url: "",
  hero_background_image_url: "",
  our_take_image_url: "",
  our_take_image_alt: "",
  hidden_gems_image_url: "",
  hidden_gems_image_alt: "",
});
