-- Seed village image alt text for all five live villages

UPDATE villages SET
  alt_text = 'Arlington Row and the River Coln, Bibury',
  our_take_image_alt = 'Arlington Row cottages beside the River Coln, Bibury',
  hidden_gems_image_alt = 'Rack Isle water meadows beside the River Coln, Bibury',
  places_to_stay = '[{"name":"The Swan Hotel","category":"Riverside Classic","image_alt":"The Swan Hotel, boutique hotel in Bibury","image_url":null,"external_link":null,"location_label":"Bibury"},{"name":"The Pig","category":"Relaxed, Garden Produce","image_alt":"The Pig, boutique hotel in Barnsley","image_url":null,"external_link":null,"location_label":"3 miles"},{"name":"Lords of the Manor","category":"Country House","image_alt":"Lords of the Manor, manor house hotel in Upper Slaughter","image_url":null,"external_link":null,"location_label":"Upper Slaughter"},{"name":"The Fish Hotel","category":"Luxury Village Retreat","image_alt":"The Fish Hotel, boutique hotel in Broadway","image_url":null,"external_link":null,"location_label":"8 miles"},{"name":"Dormy House","category":"Spa Escape","image_alt":"Dormy House, spa hotel in Broadway","image_url":null,"external_link":null,"location_label":"Broadway"}]'::jsonb,
  places_to_eat = '[{"name":"The Swan Hotel","category":"Seasonal Dining","image_alt":"The Swan Hotel, restaurants in Bibury","image_url":null,"external_link":null,"location_label":"Bibury"},{"name":"The Catherine Wheel","category":"Traditional Pub","image_alt":"The Catherine Wheel, gastropub in Bibury","image_url":null,"external_link":null,"location_label":"Bibury"},{"name":"Trout Farm Cafe","category":"Riverside Lunch","image_alt":"Trout Farm Cafe, farm shop and cafe in Bibury","image_url":null,"external_link":null,"location_label":"Bibury"},{"name":"Lords of the Manor","category":"Afternoon Tea","image_alt":"Lords of the Manor, afternoon tea in Upper Slaughter","image_url":null,"external_link":null,"location_label":"Upper Slaughter"},{"name":"The Wild Rabbit","category":"Organic Pub","image_alt":"The Wild Rabbit, restaurants in Kingham","image_url":null,"external_link":null,"location_label":"12 miles"}]'::jsonb,
  curated_experiences = '[{"body":"","title":"Arlington Row","image_alt":"Arlington Row, country walk in Bibury","image_url":null,"insider_tip":""},{"body":"","title":"Bibury Trout Farm","image_alt":"Bibury Trout Farm, family in Bibury","image_url":null,"insider_tip":""},{"body":"","title":"Rack Isle and the River Coln","image_alt":"Rack Isle and the River Coln, country walk in Bibury","image_url":null,"insider_tip":""}]'::jsonb,
  combine_with = '[{"body":"Morning in Bibury, then 15 minutes to Burford for High Street browsing, lunch and St John the Baptist Church. About 12 miles apart.","title":"Bibury + Burford","duration_label":"Morning Outing","left_image_alt":"Burford, Cotswolds village","left_image_url":"","right_image_alt":"Burford, Cotswolds village","right_image_url":""},{"body":"Early Bibury at dawn, then Castle Combe for afternoon light on the bridge and Market Cross. Allow 45 minutes between villages.","title":"Bibury + Castle Combe","duration_label":"Half Day","left_image_alt":"Castle Combe, Cotswolds village","left_image_url":"","right_image_alt":"Castle Combe, Cotswolds village","right_image_url":""},{"body":"Spread across two days if possible. Day one: Bibury and Burford. Day two: Bourton-on-the-Water and Stow-on-the-Wold. Base in Burford or Bibury.","title":"Bibury + Bourton-on-the-Water + Stow-on-the-Wold","duration_label":"Weekend","left_image_alt":"Bourton-on-the-Water, Cotswolds village","left_image_url":"","right_image_alt":"Stow-on-the-Wold, Cotswolds village","right_image_url":""}]'::jsonb,
  nearby_villages = '[{"image_alt":"Bourton-on-the-Water, Cotswolds village","image_url":null,"village_name":"Bourton-on-the-Water","drive_time_label":"15 Mins Away"},{"image_alt":"Burford, Cotswolds village","image_url":null,"village_name":"Burford","drive_time_label":"12 Mins Away"}]'::jsonb,
  comparison_stats = '[{"food":"Limited","beauty":"Exceptional","crowds":"High","image_alt":"Bibury, Cotswolds village","image_url":null,"is_current":true,"time_needed":"2-3 hours","village_name":"Bibury"},{"food":"Good","beauty":"High","crowds":"Moderate","image_alt":"Burford, Cotswolds village","image_url":null,"is_current":false,"time_needed":"2-4 hours","village_name":"Burford"},{"food":"Strong","beauty":"Very High","crowds":"Very High","image_alt":"Bourton-on-the-Water, Cotswolds village","image_url":null,"is_current":false,"time_needed":"2-3 hours","village_name":"Bourton-on-the-Water"}]'::jsonb
WHERE slug = 'bibury';

UPDATE villages SET
  alt_text = 'Stone bridges over the River Windrush, Bourton-on-the-Water',
  our_take_image_alt = 'The River Windrush running through Bourton-on-the-Water',
  hidden_gems_image_alt = 'Quiet lanes and riverside paths around Bourton-on-the-Water',
  places_to_stay = '[{"name":"The Dial House","category":"High Street Hotel","image_alt":"The Dial House, boutique hotel in Bourton-on-the-Water","image_url":null,"external_link":"https://dialhousehotel.com/","location_label":"Bourton-on-the-Water"},{"name":"Chester House Hotel","category":"Central Village Hotel","image_alt":"Chester House Hotel, boutique hotel in Bourton-on-the-Water","image_url":null,"external_link":"https://chesterhousehotel.com/","location_label":"Bourton-on-the-Water"},{"name":"The Old New Inn","category":"Boutique Hotel","image_alt":"The Old New Inn, inn in Bourton-on-the-Water","image_url":null,"external_link":"https://www.theoldnewinn.co.uk/","location_label":"Bourton-on-the-Water"},{"name":"The Lansdowne","category":"Guest House","image_alt":"The Lansdowne, boutique hotel in Bourton-on-the-Water","image_url":null,"external_link":"https://www.lansdownevilla.co.uk/","location_label":"Bourton-on-the-Water"}]'::jsonb,
  places_to_eat = '[{"name":"Smiths of Bourton","category":"Burger Restaurant","image_alt":"Smiths of Bourton, restaurants in Bourton-on-the-Water","image_url":null,"external_link":"https://www.smithsofbourton.com/","location_label":"Bourton-on-the-Water"},{"name":"Bakery on the Water","category":"Bakery and Cafe","image_alt":"Bakery on the Water, farm shop and cafe in Bourton-on-the-Water","image_url":null,"external_link":"https://www.bakeryonthewater.co.uk/","location_label":"Bourton-on-the-Water"},{"name":"The Mousetrap Inn","category":"Pub and Restaurant","image_alt":"The Mousetrap Inn, gastropub in Bourton-on-the-Water","image_url":null,"external_link":"https://www.themousetrapinn.co.uk/","location_label":"Bourton-on-the-Water"},{"name":"The Old New Inn","category":"Inn and Restaurant","image_alt":"The Old New Inn, gastropub in Bourton-on-the-Water","image_url":null,"external_link":"https://www.theoldnewinn.co.uk/","location_label":"Bourton-on-the-Water"},{"name":"The Dial House","category":"Hotel Restaurant","image_alt":"The Dial House, restaurants in Bourton-on-the-Water","image_url":null,"external_link":"https://dialhousehotel.com/","location_label":"Bourton-on-the-Water"}]'::jsonb,
  curated_experiences = '[{"body":"The low stone bridges crossing the Windrush through the village centre are the reason Bourton picked up its Venice nickname. Before 10am they are wonderfully photogenic; by midday in summer they are often busy, with people traffic waiting to cross.","title":"The River Windrush and the Five Bridges","image_alt":"The River Windrush and the Five Bridges, country walk in Bourton-on-the-Water","image_url":null,"insider_tip":"The quietest stretch is upstream from the main bridge cluster, beyond the car park end of the village."},{"body":"A proper bird park with penguins, flamingos and a wide range of species on a 9-acre site. Fully wheelchair accessible with a Changing Places Toilet. Admission from £14.95 adult in 2026; check current prices before travelling.","title":"Birdland Park and Gardens","image_alt":"Birdland Park and Gardens, family in Bourton-on-the-Water","image_url":null,"insider_tip":"Dogs on leads are welcome, which makes it a practical option if you are travelling with a dog."},{"body":"An indoor museum with a strong collection of vintage vehicles, automobilia and the original Brum car. Open daily 10am to 6pm (last admission 5:15pm). Admission around £9.95 adult in 2026.","title":"Cotswold Motoring Museum","image_alt":"Cotswold Motoring Museum, unique experiences in Bourton-on-the-Water","image_url":null,"insider_tip":"One of the better rainy-day options in Bourton: entirely indoor and reliably open."}]'::jsonb,
  combine_with = '[{"body":"The signed 5.4-mile circular walk links all three villages. Drive to Bourton, walk to the Slaughters and back. Allows you to leave the busiest part of Bourton and see two quieter villages in the same outing.","title":"Bourton-on-the-Water + Lower and Upper Slaughter","duration_label":"Half Day","left_image_alt":"Lower and Upper Slaughter, Cotswolds village","left_image_url":"","right_image_alt":"Lower and Upper Slaughter, Cotswolds village","right_image_url":""},{"body":"Two of the Cotswolds most visited villages, about 12 miles apart. Bourton for attractions and eating options, Bibury for Arlington Row and the River Coln. Start early in Bibury before the coaches arrive, then drive to Bourton for lunch.","title":"Bourton-on-the-Water + Bibury","duration_label":"Day Out","left_image_alt":"Bibury, Cotswolds village","left_image_url":"","right_image_alt":"Bibury, Cotswolds village","right_image_url":""},{"body":"Stow is about 4 miles north and adds independent shops, antique dealers and a proper market square. Pair the family attractions of Bourton with a quieter afternoon browse in Stow.","title":"Bourton-on-the-Water + Stow-on-the-Wold","duration_label":"Day Out","left_image_alt":"Stow-on-the-Wold, Cotswolds village","left_image_url":"","right_image_alt":"Stow-on-the-Wold, Cotswolds village","right_image_url":""}]'::jsonb,
  nearby_villages = '[{"image_alt":"Lower Slaughter, Cotswolds village","image_url":null,"village_name":"Lower Slaughter","drive_time_label":"5 Mins Away"},{"image_alt":"Upper Slaughter, Cotswolds village","image_url":null,"village_name":"Upper Slaughter","drive_time_label":"8 Mins Away"}]'::jsonb,
  comparison_stats = '[{"food":"Strong","beauty":"Very High","crowds":"Very High","image_alt":"Bourton-on-the-Water, Cotswolds village","image_url":null,"is_current":true,"time_needed":"2-3 hours","village_name":"Bourton-on-the-Water"},{"food":"Limited","beauty":"Exceptional","crowds":"High","image_alt":"Bibury, Cotswolds village","image_url":null,"is_current":false,"time_needed":"1-2 hours","village_name":"Bibury"},{"food":"Limited","beauty":"High","crowds":"Moderate","image_alt":"Lower Slaughter, Cotswolds village","image_url":null,"is_current":false,"time_needed":"1-2 hours","village_name":"Lower Slaughter"}]'::jsonb
WHERE slug = 'bourton-on-the-water';

UPDATE villages SET
  alt_text = 'Medieval high street on the hill, Burford',
  our_take_image_alt = 'Burford high street with limestone shop fronts',
  hidden_gems_image_alt = 'Side lanes and churchyard paths in Burford',
  places_to_stay = '[{"name":"The Bull Burford","category":"Boutique High Street Hotel","image_alt":"The Bull Burford, boutique hotel in Burford","image_url":null,"external_link":"https://www.bullburford.com/","location_label":"Burford High Street"},{"name":"The Lamb Inn","category":"Historic Cotswold Inn","image_alt":"The Lamb Inn, inn in Great Rissington","image_url":null,"external_link":"https://www.cotswold-inns-hotels.co.uk/the-lamb-inn","location_label":"Sheep Street, Burford"},{"name":"The Bay Tree","category":"4-Star Hotel","image_alt":"The Bay Tree, inn in Burford","image_url":null,"external_link":"https://www.cotswold-inns-hotels.co.uk/the-bay-tree-hotel","location_label":"Burford"},{"name":"The Angel at Burford","category":"Pub with Rooms","image_alt":"The Angel at Burford, inn in Burford","image_url":null,"external_link":"https://theangelatburford.co.uk/","location_label":"Witney Street, Burford"}]'::jsonb,
  places_to_eat = '[{"name":"The Highway Inn","category":"Tapas Bar and Inn","image_alt":"The Highway Inn, gastropub in Burford","image_url":null,"external_link":"https://www.highwayburford.com/","location_label":"Burford High Street"},{"name":"Spice Lounge","category":"Indian Restaurant","image_alt":"Spice Lounge, restaurants in Burford","image_url":null,"external_link":"https://www.thespiceloungeburford.co.uk/","location_label":"Burford"},{"name":"The Angel at Burford","category":"Pub and Restaurant","image_alt":"The Angel at Burford, gastropub in Burford","image_url":null,"external_link":"https://theangelatburford.co.uk/","location_label":"Witney Street"},{"name":"Lynwood and Co","category":"Cafe","image_alt":"Lynwood and Co, farm shop and cafe in Burford","image_url":null,"external_link":"https://www.lynwoodandco.com/","location_label":"Burford"},{"name":"Huffkins Burford","category":"Bakery and Tearoom","image_alt":"Huffkins Burford, farm shop and cafe in Burford","image_url":null,"external_link":"https://huffkins.com/pages/burford-cafe-bakery","location_label":"Burford High Street"}]'::jsonb,
  curated_experiences = '[{"body":"A sloping stone street running from the top of town down to the River Windrush and medieval bridge. Independent shops, pubs and cafes line both sides. It is the practical centre of any Burford visit and works better on foot than by car.","title":"Burford High Street","image_alt":"Burford High Street, country walk in Burford","image_url":null,"insider_tip":"Walk the full length to the bridge first, then work back uphill. Most visitors start at the top and run out of energy before they reach the river."},{"body":"Norman origins, open daily 9am to 5pm and free to enter. More than 100,000 visitors a year and one of the most historically significant churches in the Cotswolds. The Levellers connection from 1649 is documented inside.","title":"St John the Baptist Church","image_alt":"St John the Baptist Church, historic houses in Burford","image_url":null,"insider_tip":"Most day-trippers walk past it. Allow at least 30 minutes and read the Levellers history before you leave."},{"body":"A proper wildlife park 2 miles south of Burford on the A361, with rhinos, zebras, giraffes, big cats and penguins across 160 acres. Paid admission from £17.50 adult and £12.50 child in 2026. Allow at least half a day.","title":"Cotswold Wildlife Park","image_alt":"Cotswold Wildlife Park, family in Burford","image_url":null,"insider_tip":"Check current prices and book online before you go. The park is genuinely large and not easily rushed."}]'::jsonb,
  combine_with = '[{"body":"About 12 miles apart. Start early in Bibury for Arlington Row before the coaches arrive, then drive to Burford for lunch, the church and the High Street. Two very different Cotswolds experiences in one day.","title":"Burford + Bibury","duration_label":"Day Out","left_image_alt":"Bibury, Cotswolds village","left_image_url":"","right_image_alt":"Bibury, Cotswolds village","right_image_url":""},{"body":"About 12 miles apart. Burford for the High Street and church, Bourton for the river bridges and family attractions. Both have free or structured parking, making the logistics straightforward.","title":"Burford + Bourton-on-the-Water","duration_label":"Day Out","left_image_alt":"Bourton-on-the-Water, Cotswolds village","left_image_url":"","right_image_alt":"Bourton-on-the-Water, Cotswolds village","right_image_url":""},{"body":"Swinbrook is about 2 miles east along the River Windrush. A 6.2-mile signed walking route links the two. Swinbrook is quieter, has the Mitford sisters'' graves at St Mary''s church, and pairs well as a gentler afternoon follow-up to Burford.","title":"Burford + Swinbrook","duration_label":"Half Day","left_image_alt":"Swinbrook, Cotswolds village","left_image_url":"","right_image_alt":"Swinbrook, Cotswolds village","right_image_url":""}]'::jsonb,
  nearby_villages = '[{"image_alt":"Swinbrook, Cotswolds village","image_url":null,"village_name":"Swinbrook","drive_time_label":"5 Mins Away"},{"image_alt":"Bibury, Cotswolds village","image_url":null,"village_name":"Bibury","drive_time_label":"12 Mins Away"}]'::jsonb,
  comparison_stats = '[{"food":"Good","beauty":"High","crowds":"Moderate","image_alt":"Burford, Cotswolds village","image_url":null,"is_current":true,"time_needed":"2-4 hours","village_name":"Burford"},{"food":"Strong","beauty":"Very High","crowds":"Very High","image_alt":"Bourton-on-the-Water, Cotswolds village","image_url":null,"is_current":false,"time_needed":"2-3 hours","village_name":"Bourton-on-the-Water"},{"food":"Limited","beauty":"Exceptional","crowds":"High","image_alt":"Bibury, Cotswolds village","image_url":null,"is_current":false,"time_needed":"1-2 hours","village_name":"Bibury"}]'::jsonb
WHERE slug = 'burford';

UPDATE villages SET
  alt_text = 'Honey-coloured cottages around the market cross, Castle Combe',
  our_take_image_alt = 'Castle Combe village street with Cotswold stone cottages',
  hidden_gems_image_alt = 'By Brook valley walk below Castle Combe',
  places_to_stay = '[{"name":"The Manor House","category":"Luxury Country House Hotel","image_alt":"The Manor House, manor house hotel in Castle Combe","image_url":null,"external_link":"https://www.exclusive.co.uk/the-manor-house/","location_label":"Castle Combe"},{"name":"The Castle Inn","category":"Village Inn","image_alt":"The Castle Inn, inn in Castle Combe","image_url":null,"external_link":"https://www.exclusive.co.uk/the-castle-inn/","location_label":"Market Place, Castle Combe"},{"name":"The White Hart","category":"Coaching Inn","image_alt":"The White Hart, historic inn in Ford","image_url":null,"external_link":"https://www.whitehart-ford.com/","location_label":"Ford (5 mins)"}]'::jsonb,
  places_to_eat = '[{"name":"Bybrook","category":"Michelin-Listed Restaurant","image_alt":"Bybrook, restaurants in Castle Combe","image_url":null,"external_link":"https://www.exclusive.co.uk/bybrook/","location_label":"Castle Combe"},{"name":"The Castle Inn","category":"Village Pub and Restaurant","image_alt":"The Castle Inn, gastropub in Castle Combe","image_url":null,"external_link":"https://www.exclusive.co.uk/the-castle-inn/","location_label":"Market Place"},{"name":"The Salutation Inn","category":"Country Pub","image_alt":"The Salutation Inn, gastropub in Castle Combe","image_url":null,"external_link":"https://thesalutationinn.com/","location_label":"The Gibb (1km)"},{"name":"The Old Stables Coffee Shop","category":"Cafe","image_alt":"The Old Stables Coffee Shop, farm shop and cafe in Castle Combe","image_url":null,"external_link":"https://www.theoldstables.co.uk/","location_label":"The Estate Yard"},{"name":"The Little Picnic Shop","category":"Picnic and Afternoon Tea","image_alt":"The Little Picnic Shop, afternoon tea in Castle Combe","image_url":null,"external_link":"https://www.facebook.com/littlepicnicshop/","location_label":"Castle Combe"}]'::jsonb,
  curated_experiences = '[{"body":"The 14th-century Market Cross stands where the three principal streets of the lower village converge. This is the recognised film-location view, the most-photographed part of Castle Combe and the centre of any visit.","title":"The Market Cross and Lower Village","image_alt":"The Market Cross and Lower Village, historic houses in Castle Combe","image_url":null,"insider_tip":"Most visitors come for this view alone. Walk the full lower street and cross the By Brook bridge before turning back, as the scene changes completely away from the main cluster."},{"body":"","title":"Manor House Walks","image_alt":"Manor House Walks, country walk in Castle Combe","image_url":null,"insider_tip":""},{"body":"A signed walking route follows By Brook beyond the lower village through Long Dean, Nettleton Mill and gentle climbs. It covers ground most visitors never reach and is the best way to extend a Castle Combe visit beyond the central street.","title":"The By Brook Valley Walk","image_alt":"The By Brook Valley Walk, country walk in Castle Combe","image_url":null,"insider_tip":"The walk to Ford takes around 60 to 90 minutes one way and passes through countryside that makes the village make more sense historically."}]'::jsonb,
  combine_with = '[{"body":"Lacock is about 8 miles southeast and almost entirely owned by the National Trust, with Lacock Abbey and a filming history of its own. Two of the most recognised historic villages in Wiltshire in one outing.","title":"Castle Combe + Lacock","duration_label":"Half Day","left_image_alt":"Lacock, Cotswolds village","left_image_url":"","right_image_alt":"Lacock, Cotswolds village","right_image_url":""},{"body":"Biddestone is 4 miles away and connected by a Cotswolds National Landscape walking route through Slaughterford and the By Brook valley. Quieter and less visited than Castle Combe, it makes a natural second stop.","title":"Castle Combe + Biddestone","duration_label":"Half Day","left_image_alt":"Biddestone, Cotswolds village","left_image_url":"","right_image_alt":"Biddestone, Cotswolds village","right_image_url":""},{"body":"Both villages are regularly named the most beautiful in England. They are around 25 miles apart. Pair them for a day focused on two contrasting types of Cotswolds beauty.","title":"Castle Combe + Bibury","duration_label":"Day Out","left_image_alt":"Bibury, Cotswolds village","left_image_url":"","right_image_alt":"Bibury, Cotswolds village","right_image_url":""}]'::jsonb,
  nearby_villages = '[{"image_alt":"Biddestone, Cotswolds village","image_url":null,"village_name":"Biddestone","drive_time_label":"10 Mins Away"},{"image_alt":"Lacock, Cotswolds village","image_url":null,"village_name":"Lacock","drive_time_label":"15 Mins Away"}]'::jsonb,
  comparison_stats = '[{"food":"Limited","beauty":"Exceptional","crowds":"High","image_alt":"Castle Combe, Cotswolds village","image_url":null,"is_current":true,"time_needed":"1-2 hours","village_name":"Castle Combe"},{"food":"Limited","beauty":"Exceptional","crowds":"High","image_alt":"Bibury, Cotswolds village","image_url":null,"is_current":false,"time_needed":"1-2 hours","village_name":"Bibury"},{"food":"Strong","beauty":"Very High","crowds":"Very High","image_alt":"Bourton-on-the-Water, Cotswolds village","image_url":null,"is_current":false,"time_needed":"2-3 hours","village_name":"Bourton-on-the-Water"}]'::jsonb
WHERE slug = 'castle-combe';

UPDATE villages SET
  alt_text = 'Stone cottages below the Cotswold escarpment, Snowshill',
  our_take_image_alt = 'Snowshill village lane with stone cottages',
  hidden_gems_image_alt = 'Cotswold Lavender fields near Snowshill',
  places_to_stay = '[{"name":"Foxhill Manor","category":"5-Star All-Inclusive Private House Hotel","image_alt":"Foxhill Manor, exclusive use in Broadway","image_url":null,"external_link":"https://foxhillmanor.com/","location_label":"Farncombe Estate, Broadway (5 mins)"},{"name":"Dormy House","category":"Luxury Spa Hotel","image_alt":"Dormy House, spa hotel in Broadway","image_url":null,"external_link":"https://dormyhouse.co.uk/","location_label":"Farncombe Estate, Broadway (5 mins)"},{"name":"The Fish Hotel","category":"Luxury Estate Hotel","image_alt":"The Fish Hotel, boutique hotel in Broadway","image_url":null,"external_link":"https://thefishhotel.co.uk/","location_label":"Farncombe Estate, Broadway (5 mins)"},{"name":"Buckland Manor","category":"13th-Century Country House Hotel","image_alt":"Buckland Manor, manor house hotel in Buckland","image_url":null,"external_link":"https://bucklandmanor.co.uk/","location_label":"Buckland, nr Broadway (8 mins)"}]'::jsonb,
  places_to_eat = '[{"name":"Snowshill Arms","category":"Village Pub","image_alt":"Snowshill Arms, gastropub in Snowshill","image_url":null,"external_link":"https://www.snowshillarms.co.uk/","location_label":"Snowshill village"},{"name":"Snowshill Manor Cafe","category":"National Trust Cafe","image_alt":"Snowshill Manor Cafe, farm shop and cafe in Snowshill","image_url":null,"external_link":"https://www.nationaltrust.org.uk/visit/gloucestershire-cotswolds/snowshill-manor-and-garden","location_label":"Snowshill Manor"},{"name":"Cotswold Lavender Cabin","category":"Seasonal Snack Cabin","image_alt":"Cotswold Lavender Cabin, farm shop and cafe in Snowshill","image_url":null,"external_link":"https://www.cotswoldlavender.co.uk/pages/visit","location_label":"Hill Barn Farm"}]'::jsonb,
  curated_experiences = '[{"body":"The former home of designer Charles Paget Wade, filled with his collection of handmade objects, armour, model villages, costume and mechanical items. The Arts and Crafts garden was designed in 1920 with architect Mackay Hugh Baillie Scott. Adult admission £18 without Gift Aid. Free parking 500 yards from the Manor.","title":"Snowshill Manor and Garden","image_alt":"Snowshill Manor and Garden, historic houses in Snowshill","image_url":null,"insider_tip":"If the Manor is busy, National Trust guidance says visitors can explore the garden before entering the Manor within their two-hour house entry slot. On busier days, timed tickets apply."},{"body":"A seasonal working lavender farm at Hill Barn Farm, Snowshill. Open 11 June to 5 August 2026, with peak flowering from 27 June onwards. Adult admission £7.75, child £3.50. Card payment only. Parking is free for patrons: follow brown signs rather than using the postcode alone.","title":"Cotswold Lavender Fields","image_alt":"Cotswold Lavender Fields, garden in Snowshill","image_url":null,"insider_tip":"Extended evening openings run on Wednesdays, Fridays and Saturdays from 1 to 18 July 2026. Groups of more than 15 should contact the farm in advance."},{"body":"A signed Cotswolds National Landscape circular route linking Snowshill, Stanton and The Edge via the Cotswold Way. The full route is 6 miles; a shorter 2.5-mile option is available. Stanton makes a natural pairing with Snowshill on a walking day.","title":"The Stanton, Snowshill and The Edge Walk","image_alt":"The Stanton, Snowshill and The Edge Walk, country walk in Snowshill","image_url":null,"insider_tip":"The route connects two of the quieter North Cotswolds villages and passes through landscape that most visitors only see from a car window."}]'::jsonb,
  combine_with = '[{"body":"Broadway is 2.4 miles by road and the practical gateway to Snowshill. Larger car parks, more places to eat, museums and shops. Start at Snowshill for the Manor or lavender in the morning, then drive down into Broadway for lunch and the afternoon.","title":"Snowshill + Broadway","duration_label":"Half Day","left_image_alt":"Broadway, Cotswolds village","left_image_url":"","right_image_alt":"Broadway, Cotswolds village","right_image_url":""},{"body":"Stanton is the most natural walking partner for Snowshill, connected by the official 6-mile Cotswolds National Landscape circular route. Stanton is quieter than Broadway and has The Mount Inn as a stopping point. Allow a full morning for the loop.","title":"Snowshill + Stanton","duration_label":"Half Day Walk","left_image_alt":"Stanton, Cotswolds village","left_image_url":"","right_image_alt":"Stanton, Cotswolds village","right_image_url":""},{"body":"Chipping Campden is around 8 miles from Snowshill and one of the strongest North Cotswolds market towns for historic streets, independent shops and the Cotswold Way. Pair a morning in Snowshill with an afternoon in Campden for a rounded North Cotswolds day.","title":"Snowshill + Chipping Campden","duration_label":"Day Out","left_image_alt":"Chipping Campden, Cotswolds village","left_image_url":"","right_image_alt":"Chipping Campden, Cotswolds village","right_image_url":""}]'::jsonb,
  nearby_villages = '[{"image_alt":"Broadway, Cotswolds village","image_url":null,"village_name":"Broadway","drive_time_label":"6 Mins Away"},{"image_alt":"Stanton, Cotswolds village","image_url":null,"village_name":"Stanton","drive_time_label":"11 Mins Away"}]'::jsonb,
  comparison_stats = '[{"food":"Very Limited","beauty":"High","crowds":"Low","image_alt":"Snowshill, Cotswolds village","image_url":null,"is_current":true,"time_needed":"1-3 hours","village_name":"Snowshill"},{"food":"Strong","beauty":"Very High","crowds":"High","image_alt":"Broadway, Cotswolds village","image_url":null,"is_current":false,"time_needed":"2-3 hours","village_name":"Broadway"},{"food":"Good","beauty":"Very High","crowds":"Moderate","image_alt":"Chipping Campden, Cotswolds village","image_url":null,"is_current":false,"time_needed":"2-3 hours","village_name":"Chipping Campden"}]'::jsonb
WHERE slug = 'snowshill';

